services:
  lt-client:
    build: ./lt-client
    container_name: lt-client
    ports:
      - "3000:3000"
    depends_on:
      - lt-server
  lt-server:
    build: ./lt-server
    container_name: lt-server
    env_file:
      - ./lt-server/.env
    ports:
      - "5000:5000"
    volumes:
      - ./lt-server:/app
      - /app/node_modules
    depends_on:
      - lt-cache
      - lt-database
  lt-cache:
    image: redis:7.0-alpine
    restart: always
    ports:
      - "6379:6379"
  lt-database:
    image: mongo:latest
    container_name: lt-database
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: lt-db
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
