name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './lt-client/package.json'
    
    - name: Install dependencies
      working-directory: ./lt-client
      run: npm ci
    
    - name: Run tests
      working-directory: ./lt-client
      run: npm test -- --passWithNoTests
    
    - name: Type Check
      working-directory: ./lt-client
      run: npm run typecheck
